import os

data_root = 'data'
save_root = 'results'

os.makedirs(save_root, exist_ok=True)

model_info = {
    'mar_small': {
        'path': os.path.join(data_root, 'velocity_model', 'mar_smal_100_310.bin'),
        'rec_path': os.path.join(data_root, 'velocity_model', 'mar_smal_100_310_rec_amp.npy'),
        'synthetic_CSEM': os.path.join(data_root, 'resistivity_model', 'mar_s_CSEM_inv_r.npy'),
        'r_info': {'min': 10, 'max': 1000},  # resistivity range
        'grid_info': {
            'n_offset': 310,       # offset domain 310*30=9300
            'n_depth': 100,        # depth domain  100*30=3000
            'dx': 30               # grid interval
            }, 
        'wave_info': {
            'freq': 5,             # frequency of wavelet
            'nt': 2000,            # sampling number
            'dt': 0.003,           # sampling interval
            'peak_time': 1.5/5,    # amplitude
            },
        'src_info': {
            'n_shots': 31,            # shot number
            'n_sources_per_shot': 1,  # source number in each shot
            'd_source': 10,           # interval of sources
            'first_source': 0,        # the location of the first source
            'source_depth': 0,        # the depth of sources 
            },
        'rec_info': {
            'n_receivers_per_shot': 310,  # receiver number in each shot
            'd_receiver': 1,              # interval of receivers
            'first_receiver': 0,          # the location of the first receiver
            'receiver_depth': 0,          # the depth of receivers 
        }
    }
}

# initial model generated by the SA method[*] 
SA_init_model = 'others/init_models/SA_init_vel_model.npy'

# [*] reference: Mendes, R., Kaelin, B., Martínez-Sansigre, A., Barbosa, V. C., Bentes, C., & Amorim, C. L. (2024). Faster determination of an initial velocity model for full-waveform inversion based on simulated annealing. Geophysics, 89(3), R187-R198.